// Generates src/data/catalog.ts from the PlanToys public Shopify catalog.
// Downloads each product's main image to public/products/<slug>.jpg.
// Run: node scripts/gen-catalog.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const imgDir = path.join(root, "public", "products");
fs.mkdirSync(imgDir, { recursive: true });

// Category detection by keyword (order matters).
function categorize(title) {
  const t = title.toLowerCase();
  const has = (...w) => w.some((x) => t.includes(x));
  if (has("dollhouse", "victorian", "georgian", "bedroom set", "living room", "dining room", "kitchen set", "bathroom set", "slide n go", "planspace")) return "puppenhaus";
  if (has("boat", "submarine", "water", "bath", "sea life", "marine", "whale", "dolphin", "fountain", "speed boat", "coast guard", "sailing")) return "wasser";
  if (has("drum", "xylophone", "banjo", "whistle", "rhythm", "band", "concertina", "rain maker", "rainmaker", "bell", "musical", "clatter", "roller", "pounding", "clapper", "guitar")) return "musik";
  if (has("puzzle", "alphabet", "number", "math", "counting", "count", "sorting", "sort", "braille", "hand sign", "clock", "memo", "domino", "block", "unit", "fraction", "ten frame", "geo ", "geometric", "lacing", "peg board", "tactile", "touch")) return "lernen";
  if (has("golf", "bowling", "soccer", "petanque", "ring toss", "shuffleboard", "wall ball", "pinball", "acrobat", "balancing", "cactus", "timber tumble", "maze", "fishing", "tic-tac-toe", "pick-up", "penguin wobbler", "wobbler")) return "bewegung";
  if (has("rattle", "walker", "clutching", "wobbler", "key ", "teether", "baby", "sensory", "twist & sort", "twist and sort", "square clutching")) return "baby";
  if (has("push", "pull", "vroom", "racer", "car", "bus", "truck", "duck racer", "walk n roll", "walk-n-roll", "stroller", "wagon", "delivery bike", "rocking", "pegasus", "palomino", "train")) return "fahren";
  if (has("nuts", "bolts", "gears", "workbench", "robot", "construction", "tool", "crane", "screw")) return "bauen";
  // pretend play catch-all: dolls, food sets, role play, camera, phone
  return "rollenspiel";
}

// Prices (EUR) that must match the customer invoice RE-2026-1255.
const invoiceOverrides = {
  "victorian-dollhouse": 299,
  "road-system": 89,
  "palomino-modern-rustic": 90,
  "my-first-camera": 16,
};
const featuredHandles = new Set([
  "victorian-dollhouse",
  "road-system",
  "palomino-modern-rustic",
  "my-first-camera",
]);

async function download(url, dest) {
  try {
    const res = await fetch(url);
    if (!res.ok) return false;
    const buf = Buffer.from(await res.arrayBuffer());
    fs.writeFileSync(dest, buf);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  console.log("Fetching PlanToys catalog...");
  const res = await fetch("https://www.plantoys.com/products.json?limit=250");
  const json = await res.json();
  const raw = json.products;
  console.log("Products:", raw.length);

  const seen = new Set();
  const products = [];
  let downloaded = 0;

  for (const p of raw) {
    const slug = p.handle;
    if (seen.has(slug)) continue;
    seen.add(slug);

    const title = p.title.replace(/\?+$/, "").trim();
    let price = Math.round(parseFloat(p.variants?.[0]?.price ?? "0"));
    if (invoiceOverrides[slug] != null) price = invoiceOverrides[slug];
    if (!price) continue;

    const category = categorize(title);
    const imgUrl = p.images?.[0]?.src;
    let hasImage = false;
    if (imgUrl) {
      const ok = await download(imgUrl, path.join(imgDir, `${slug}.jpg`));
      if (ok) {
        hasImage = true;
        downloaded++;
        if (downloaded % 25 === 0) console.log("  downloaded", downloaded);
      }
    }

    products.push({
      slug,
      name: title,
      price,
      category,
      brand: "PlanToys",
      featured: featuredHandles.has(slug),
    });
  }

  console.log("Images downloaded:", downloaded, "/", products.length);

  const header = `// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Product data sourced from PlanToys public catalog for resale.
import type { CatalogProduct } from "./types";

export const generatedProducts: CatalogProduct[] = ${JSON.stringify(products, null, 2)};
`;
  fs.writeFileSync(path.join(root, "src", "data", "generated.ts"), header);
  console.log("Wrote src/data/generated.ts");
}

main();
