// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Product data sourced from PlanToys public catalog for resale.
import type { CatalogProduct } from "./types";

export const generatedProducts: CatalogProduct[] = [
  {
    "slug": "farmers-market-mix-basket",
    "name": "Farmers Market Mix Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rainbow-fiesta-basket",
    "name": "Rainbow Fiesta Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rainbow-veggie-basket",
    "name": "Rainbow Veggie Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "winter-harvest-basket",
    "name": "Winter Harvest Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sunny-orchard-basket",
    "name": "Sunny Orchard Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "berry-citrus-basket",
    "name": "Berry & Citrus Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "garden-fresh-basket",
    "name": "Garden Fresh Basket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "weightlifting-acrobat-1",
    "name": "Weightlifting Acrobat",
    "price": 22,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "nurse-doll",
    "name": "Nurse Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "life-size-tie-up-shoe",
    "name": "Life-Size Tie-Up Shoe",
    "price": 22,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "math-blocks-and-rods",
    "name": "Math Blocks And Rods",
    "price": 55,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-spa-time-set",
    "name": "My Spa Time Set",
    "price": 26,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rescue-doll",
    "name": "Rescue Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "travel-tic-tac-toe",
    "name": "Travel Tic-Tac-Toe",
    "price": 17,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "firefighter-doll",
    "name": "Firefighter Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doctor-doll",
    "name": "Doctor Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "victorian-kitchen-set",
    "name": "Victorian Kitchen Set",
    "price": 35,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "victorian-dining-room-set",
    "name": "Victorian Dining Room Set",
    "price": 35,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "little-tool-bench",
    "name": "Little Tool Bench",
    "price": 100,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "victorian-living-room-set",
    "name": "Victorian Living Room Set",
    "price": 35,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "gear-go-walker",
    "name": "Gear & Go Walker",
    "price": 125,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "georgian-dollhouse",
    "name": "Georgian Dollhouse",
    "price": 300,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "chef-doll",
    "name": "Chef Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "maze-game",
    "name": "Maze Game",
    "price": 17,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "service-worker-doll",
    "name": "Service Worker Doll",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "spinning-gears-playset",
    "name": "Spinning Gears Playset",
    "price": 55,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "victorian-bedroom-set",
    "name": "Victorian Bedroom Set",
    "price": 35,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "driving-console",
    "name": "Driving Console",
    "price": 60,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "victorian-bathroom-set",
    "name": "Victorian Bathroom Set",
    "price": 35,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "whale-whistle",
    "name": "Whale Whistle",
    "price": 8,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dolphin-whistle",
    "name": "Dolphin Whistle",
    "price": 8,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "palomino",
    "name": "Palomino",
    "price": 120,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doll-family",
    "name": "Doll Family - Medium Skin Tone",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "delivery-bike-orchard-collection",
    "name": "Delivery Bike - Orchard",
    "price": 200,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "hopping-rabbit",
    "name": "Hopping Rabbit",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-wheels",
    "name": "Stacking Wheels",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "bunny-racing-car",
    "name": "Bunny Racing Car",
    "price": 31,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "assorted-fruit-vegetable",
    "name": "Assorted Fruit & Vegetable",
    "price": 40,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-pelican",
    "name": "Push-Along Pelican",
    "price": 35,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "van-walker",
    "name": "Van Walker",
    "price": 80,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "breakfast-menu",
    "name": "Breakfast Menu",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "cooking-utensils-set",
    "name": "Cooking Utensils Set",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sailing-boat-seal",
    "name": "Sailing Boat - Seal",
    "price": 18,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sailing-boat-penguin",
    "name": "Sailing Boat - Penguin",
    "price": 18,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sailing-boat-polar-bear",
    "name": "Sailing Boat - Polar Bear",
    "price": 18,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fountain-bowl-set",
    "name": "Fountain Bowl Set",
    "price": 25,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "2-in-1-shuffleboard-game",
    "name": "2-In-1 Shuffleboard Game",
    "price": 45,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "chicken-racing-car",
    "name": "Chicken Racing Car",
    "price": 30,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "timber-tumble",
    "name": "Timber Tumble",
    "price": 30,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "magnetic-board-game",
    "name": "Magnetic Board Game",
    "price": 100,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-bunny-pink",
    "name": "Push Along Bunny - Pink",
    "price": 21,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "pinball",
    "name": "Pinball",
    "price": 120,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult",
    "name": "Mom Dollhouse Figure - Medium Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "5-colors-veggie-set",
    "name": "5 Colors Veggie Set",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-1",
    "name": "Dad Dollhouse Figure - Medium Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "vroom-car",
    "name": "Vroom Car",
    "price": 22,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "soccer",
    "name": "Soccer",
    "price": 120,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-bunny-white",
    "name": "Push Along Bunny - White",
    "price": 21,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "woodpecker-walker",
    "name": "Woodpecker Walker",
    "price": 150,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "giraffe-puzzle",
    "name": "Giraffe Puzzle",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "elephant-puzzle",
    "name": "Elephant Puzzle",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-pull-puppy",
    "name": "Push & Pull Puppy",
    "price": 50,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "walk-n-roll-orchard-series",
    "name": "Walk N Roll - Orchard",
    "price": 35,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dog-puzzle",
    "name": "Dog Puzzle",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "vroom-bus",
    "name": "Vroom Bus",
    "price": 22,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-logs",
    "name": "Stacking Logs",
    "price": 18,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "vroom-truck",
    "name": "Vroom Truck",
    "price": 22,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-2",
    "name": "Dad Dollhouse Figure - Light Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child",
    "name": "Boy Dollhouse Figure - Dark Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-1",
    "name": "Girl Dollhouse Figure - Dark Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-3",
    "name": "Mom Dollhouse Figure - Dark Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-4",
    "name": "Dad Dollhouse Figure - Dark Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-2",
    "name": "Boy Dollhouse Figure - Light Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-3",
    "name": "Girl Dollhouse Figure - Light Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-5",
    "name": "Mom Dollhouse Figure - Light Skin Toneㅤ",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-adult-6",
    "name": "Dad Dollhouse Figure - Fair Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-4",
    "name": "Boy Dollhouse Figure - Medium Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-5",
    "name": "Girl Dollhouse Figure - Medium Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "food-beverage-set",
    "name": "Food & Beverage Set",
    "price": 22,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dino-puzzle",
    "name": "Dino Puzzle",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-bunny-light-blue",
    "name": "Push Along Bunny - Blue",
    "price": 21,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-bunny-brown",
    "name": "Push Along Bunny - Brown",
    "price": 18,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sea-life-puzzle",
    "name": "Sea Life Puzzle",
    "price": 20,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-bunny-gray",
    "name": "Push Along Bunny - Grey",
    "price": 18,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "animal-puzzle-game",
    "name": "Animal Puzzle Game",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "finding-penguin-game",
    "name": "Finding Penguin Game",
    "price": 35,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "celebration-train",
    "name": "Celebration Train",
    "price": 35,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fishing-game",
    "name": "Fishing Gameㅤ",
    "price": 30,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "bowling-set",
    "name": "Bowling Set",
    "price": 70,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "petanque",
    "name": "Petanque",
    "price": 30,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "wall-ball-game",
    "name": "Wall Ball Game",
    "price": 90,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-train-trio-orchard-collection",
    "name": "Stacking Train Trio - Orchard",
    "price": 61,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doctor-set",
    "name": "Doctor Set",
    "price": 45,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fishing-game-1",
    "name": "Fishing Game",
    "price": 25,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-6",
    "name": "Boy Dollhouse Figure - Fair Skin Toneㅤ",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "50-unit-blocks",
    "name": "50 Unit Blocks",
    "price": 90,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "push-along-duck",
    "name": "Push Along Duck",
    "price": 36,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "40-unit-blocks-pastel-series",
    "name": "40 Unit Blocks",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "number-1-10-gradient",
    "name": "Number 1-10 (Gradient)",
    "price": 25,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geometric-sorting",
    "name": "Geometric Sorting",
    "price": 25,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geo-stacking-rock",
    "name": "Geo Stacking Rock",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-first-camera",
    "name": "My First Camera",
    "price": 16,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": true
  },
  {
    "slug": "colorful-40-unit-blocks",
    "name": "40 Unit Blocksㅤ",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "alphabet-a-z-gradient",
    "name": "Alphabet A-Z Gradient Tiles",
    "price": 35,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fruit-veggie-domino-gradient",
    "name": "Fruit & Veggie Domino (Gradient)",
    "price": 40,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fairy-tale-blocks",
    "name": "Fairy Tale Blocks",
    "price": 40,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "activity-blocks",
    "name": "Activity Blocks",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "beehives-orchard-series",
    "name": "Beehives - Orchard",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "meadow-ring-toss",
    "name": "Meadow Ring Toss",
    "price": 36,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-first-phone-orchard",
    "name": "My First Phone - Orchard",
    "price": 13,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "tie-up-shoe-orchard-series",
    "name": "Tie-Up Shoe - Orchard",
    "price": 12,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sorting-bus-orchard-series",
    "name": "Sorting Bus - Orchard",
    "price": 60,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-rocket-orchard-series",
    "name": "Stacking Rocket - Orchard",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "water-blocks",
    "name": "Water Blocks",
    "price": 80,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sort-count-trees",
    "name": "Sort & Count Trees",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "spatial-rocket",
    "name": "Spatial Rocket",
    "price": 27,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "number-and-symbols",
    "name": "Numbers And Symbols",
    "price": 30,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "upper-case-alphabet",
    "name": "Upper Case Alphabet",
    "price": 60,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "lower-case-alphabet",
    "name": "Lower Case Alphabet",
    "price": 60,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "kaleidoscope",
    "name": "Kaleidoscope",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "robot-toolbox",
    "name": "Robot Toolbox",
    "price": 50,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "workbench",
    "name": "Workbench",
    "price": 90,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "creative-blocks-orchard-series",
    "name": "Creative Blocks - Orchard",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "castle-blocks-orchard-series",
    "name": "Castle Blocks - Orchard",
    "price": 60,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "ice-cream-set",
    "name": "Ice Cream Set",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "tool-belt",
    "name": "Tool Belt",
    "price": 30,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rocking-pegasus",
    "name": "Rocking Pegasus",
    "price": 125,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "delivery-bike",
    "name": "Delivery Bike",
    "price": 171,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-first-camera-orchard",
    "name": "My First Camera - Orchard",
    "price": 15,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "braille-numbers-1-10",
    "name": "Braille Numbers 1-10",
    "price": 25,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "hand-sign-numbers-1-10",
    "name": "Hand Sign Numbers 1-10",
    "price": 25,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-mood-memo",
    "name": "My Mood Memo",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "animal-set",
    "name": "Animal Set",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "camping-set",
    "name": "Camping Set",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sea-life-bath-set",
    "name": "Sea Life Bath Set",
    "price": 30,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "tree-house",
    "name": "Tree House",
    "price": 31,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "construction-set",
    "name": "Construction Set",
    "price": 60,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "braille-alphabet-a-z",
    "name": "Braille Alphabet A-Z",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "puzzle-cube",
    "name": "Puzzle Cube",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "hand-sign-alphabet-a-z",
    "name": "Hand Sign Alphabet A-Z",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "chicken-puzzle",
    "name": "Chicken Puzzle",
    "price": 20,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "my-first-phone",
    "name": "My First Phone",
    "price": 18,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "balancing-cactus",
    "name": "Balancing Cactusㅤ",
    "price": 40,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "slide-n-go-dollhouse",
    "name": "Slide N Go Dollhouse",
    "price": 220,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "concertina",
    "name": "Concertina",
    "price": 36,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doll-stroller",
    "name": "Doll Stroller",
    "price": 108,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "wonky-fruit-vegetables",
    "name": "Wonky Fruit & Vegetables",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "motor-mechanic",
    "name": "Motor Mechanic",
    "price": 360,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dentist-set",
    "name": "Dentist Set",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "hair-dresser-set",
    "name": "Hair Dresser Set",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "pet-care-set",
    "name": "Pet Care Set",
    "price": 30,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "vet-set",
    "name": "Vet Set",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "bakery-stand-set",
    "name": "Bakery Stand Set",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "birthday-cake-set",
    "name": "Birthday Cake Set",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "make-up-set",
    "name": "Make Up Set",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "weather-dress-up",
    "name": "Weather Dress-Up",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "speed-boat",
    "name": "Speed Boat",
    "price": 20,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "coast-guard-boat",
    "name": "Coast Guard Boat",
    "price": 25,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dino-height",
    "name": "Dino Height",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "submarine",
    "name": "Submarine",
    "price": 25,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "mini-camera",
    "name": "Mini Camera",
    "price": 6,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-ring-mouse",
    "name": "Stacking Ring - Mouse",
    "price": 22,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "musical-band",
    "name": "Musical Band",
    "price": 80,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "mini-golf-full-set",
    "name": "Mini Golf - Full Set",
    "price": 45,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "piggy-bank-yellow",
    "name": "Piggy Bank Yellow - Orchard",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "penguin",
    "name": "Penguin Wobbler",
    "price": 18,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "big-drum-ii",
    "name": "Big Drum II",
    "price": 45,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "banjo",
    "name": "Banjo",
    "price": 40,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doll-feeding-set",
    "name": "Doll Feeding Set",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "cleaning-set",
    "name": "Cleaning Set",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "table-chair-black",
    "name": "Table & Chair - Black",
    "price": 240,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "leaf-magnifier",
    "name": "Leaf Magnifier",
    "price": 18,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "duck-racer",
    "name": "Duck Racer",
    "price": 15,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "oval-xylophone",
    "name": "Oval Xylophone",
    "price": 36,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "chair",
    "name": "Chair",
    "price": 80,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "solid-drum",
    "name": "Solid Drum",
    "price": 36,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "elephant-bank",
    "name": "Elephant Bank",
    "price": 40,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "piggy-bank-red",
    "name": "Piggy Bank Red - Orchard",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "tie-up-shoe",
    "name": "Tie-Up Shoe",
    "price": 15,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dino-car-stego",
    "name": "Dino Car - Stego",
    "price": 10,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "colored-snap-camera",
    "name": "Colored Snap Camera",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "tactile-stone",
    "name": "Tactile Stone",
    "price": 30,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-rocket",
    "name": "Stacking Rocket",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "touch-guess",
    "name": "Touch & Guess",
    "price": 27,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rubber-road-rail-set-small",
    "name": "Rubber Road & Rail Set - Small",
    "price": 50,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "chicken-nesting",
    "name": "Chicken Nesting",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rhythm-box",
    "name": "Rhythm Box",
    "price": 50,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "miracle-pounding-ii",
    "name": "Miracle Pounding II",
    "price": 45,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "bell-rattle",
    "name": "Bell Rattleㅤ",
    "price": 15,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "musical-set",
    "name": "Musical Set",
    "price": 65,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "nuts-bolts",
    "name": "Nuts & Bolts",
    "price": 36,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rubber-road-rail-set-large",
    "name": "Rubber Road & Rail Set - Large",
    "price": 140,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "marine-puzzle",
    "name": "Marine Puzzle",
    "price": 25,
    "category": "wasser",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "clatter",
    "name": "Clatter",
    "price": 30,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "balancing-cactus-1",
    "name": "Mini Balancing Cactus",
    "price": 15,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "roller",
    "name": "Roller - Classic",
    "price": 18,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "spinning-tops",
    "name": "Mini Spinning Tops",
    "price": 15,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "baby-walker-orchard-collection",
    "name": "Baby Walker - Orchard",
    "price": 112,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "nesting-puzzle-unit-plus",
    "name": "Nesting Puzzle - Unit Plus",
    "price": 70,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "happy-puppy",
    "name": "Happy Puppy",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "colored-counting-blocks-unit-plus",
    "name": "Colored Counting Blocks - Unit Plus",
    "price": 50,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "cone-sorting-unit-plus",
    "name": "Cone Sorting - Unit Plus",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geo-lacing-beads-unit-plus",
    "name": "Geo Lacing Beads - Unit Plus",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "double-drum",
    "name": "Double Drum",
    "price": 40,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "beehives",
    "name": "Beehives",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rhythm-box-ii",
    "name": "Rhythm Box II",
    "price": 71,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "round-table",
    "name": "Round Table",
    "price": 108,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "twist-sort",
    "name": "Twist & Sort",
    "price": 30,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rainmaker",
    "name": "Rain Maker",
    "price": 25,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fruit-vegetable-play-set",
    "name": "Fruit & Vegetable Play Set",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "pick-up-sticks",
    "name": "Pick-Up Sticks - PlanMini",
    "price": 10,
    "category": "bewegung",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "activity-clock",
    "name": "Activity Clock",
    "price": 50,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rocking-chair",
    "name": "Rocking Chair",
    "price": 170,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "baby-key-rattle",
    "name": "Baby Key Rattle",
    "price": 18,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "memo-game",
    "name": "Memo Game - PlanMini",
    "price": 13,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "creative-board",
    "name": "Creative Board",
    "price": 45,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "construction-set-1",
    "name": "Construction Set - PlanMini",
    "price": 12,
    "category": "bauen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "ten-frame-unit-plus",
    "name": "Ten Frame - Unit Plus",
    "price": 45,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "oval-xylophone-orchard-series",
    "name": "Oval Xylophone - Orchard",
    "price": 30,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "punch-drop-orchard-collection",
    "name": "Punch & Drop - Orchard",
    "price": 35,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "drum-set",
    "name": "Drum Set",
    "price": 300,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "shape-sort-it-out-orchard-collection",
    "name": "Shape & Sort It Out - Orchard",
    "price": 40,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "gardening-set",
    "name": "Gardening Set",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "lacing-beads",
    "name": "Lacing Beads",
    "price": 35,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-ring-orchard-collection",
    "name": "Stacking Ring - Orchard",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "clatter-orchard-series",
    "name": "Clatter - Orchard",
    "price": 25,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sort-count-cups-orchard-collection",
    "name": "Sort & Count Cups - Orchard",
    "price": 25,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "set-of-traffic-signs-lights",
    "name": "Set Of Traffic Signs & Lights",
    "price": 25,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geometric-sorting-board-orchard-collection",
    "name": "Geometric Sorting Board - Orchard",
    "price": 27,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rubber-road-rail-extension-tracks-set-b",
    "name": "Rubber Road & Rail Expansion Tracks - Set B",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geometric-peg-board-orchard-collection",
    "name": "Geometric Peg Board - Orchard",
    "price": 22,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "rubber-road-rail-extension-tracks-set-a",
    "name": "Rubber Road & Rail Expansion Tracks - Set A",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-8",
    "name": "Boy Dollhouse Figure - Fair Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "banjolele",
    "name": "Banjolele",
    "price": 40,
    "category": "musik",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "fraction-blocks-unit-plus",
    "name": "Fraction Blocks - Unit Plus",
    "price": 36,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dancing-alligator",
    "name": "Dancing Alligator",
    "price": 36,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "100-counting-cubes-unit-plus",
    "name": "100 Counting Cubes - Unit Plus",
    "price": 70,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "dollhouse-figure-child-9",
    "name": "Girl Dollhouse Figure - Fair Skin Tone",
    "price": 8,
    "category": "puppenhaus",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "wagon-black",
    "name": "Wagon - Black",
    "price": 110,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "pull-along-snail",
    "name": "Pull Along Snail",
    "price": 36,
    "category": "fahren",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "baby-car",
    "name": "Baby Car",
    "price": 22,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sort-count-cups",
    "name": "Sort & Count Cups",
    "price": 30,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "bear",
    "name": "Bear",
    "price": 20,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sorting-bus",
    "name": "Sorting Bus",
    "price": 50,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "sensory-tumbling",
    "name": "Sensory Tumbling",
    "price": 30,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "baby-walker",
    "name": "Baby Walkerㅤ",
    "price": 112,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "square-clutching-toy",
    "name": "Square Clutching Toy",
    "price": 25,
    "category": "baby",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "stacking-ring",
    "name": "Stacking Ring",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "geometric-peg-board",
    "name": "Geometric Peg Board",
    "price": 30,
    "category": "lernen",
    "brand": "PlanToys",
    "featured": false
  },
  {
    "slug": "doll-family-1",
    "name": "Doll Family - Light Skin Tone - Blonde Hair",
    "price": 30,
    "category": "rollenspiel",
    "brand": "PlanToys",
    "featured": false
  }
];
